server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///${user.home}/native-file-repo
        git:
          uri: https://github.com/ness727/spring-cloud-config
#          username:
#          password:
